#!/bin/sh /etc/rc.common
START=1999
start(){
        echo "delay 120s for opengw start "
        sleep 120;
        /usr/share/opengw/opengw  &
}

stop(){
       killall /usr/share/opengw/opengw 
}

restart(){
        killall /usr/share/opengw/opengw && /usr/share/opengw &
}
